[build]
  base = "/"
  publish = "dist/"
  command = "yarn build"
  functions = "serverless"
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api"
  status = 200
  from = "/*"
  to = "/index.html"
  status = 200